package models

import (
	"time"
)

type Test struct {
	Id        string    `json:"id,omitempty"` // ID will be auto-generated by the database
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at,omitempty"`
	UpdatedAt time.Time `json:"updated_at,omitempty"`
}
